
---
spring:
  jpa:
    generate-ddl: true
security:
  oauth2:
    client:
      clientId: elements
      clientSecret: mendeleev
      accessTokenUri: https://7391cf8a-2d32-45f5-8884-cf36e36c3fdb.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/access_token
      userAuthorizationUri: https://7391cf8a-2d32-45f5-8884-cf36e36c3fdb.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/authorize
    resource:
      userInfoUri:  https://7391cf8a-2d32-45f5-8884-cf36e36c3fdb.predix-uaa.run.aws-usw02-pr.ice.predix.io/userinfo
      tokenInfoUri: https://7391cf8a-2d32-45f5-8884-cf36e36c3fdb.predix-uaa.run.aws-usw02-pr.ice.predix.io/check_token
