
---
spring:
  jpa:
    generate-ddl: true
security:
  oauth2:
    client:
      clientId: foo
      clientSecret: foo
      accessTokenUri: https://2f2bd91e-3b1b-4e16-9838-7f697b13c47e.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/access_token
      userAuthorizationUri: https://2f2bd91e-3b1b-4e16-9838-7f697b13c47e.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/authorize
    resource:
      userInfoUri: https://2f2bd91e-3b1b-4e16-9838-7f697b13c47e.predix-uaa.run.aws-usw02-pr.ice.predix.io/userinfo
      tokenInfoUri: https://2f2bd91e-3b1b-4e16-9838-7f697b13c47e.predix-uaa.run.aws-usw02-pr.ice.predix.io/check_token